### ISSUE TITLE
AssertionError: Results do not correspond to current coco set

### ISSUE THREAD

**Issue by lijoe123** [GitHubbeer/mmdetection_PR_curve#1]
您好，我想请教一下，我换用自己的coco数据集，和自己训练的模型，为什么会出现以下的错误：
Loading and preparing results...
Traceback (most recent call last):
  File "/home/music/Downloads/mmdetection/pr_curve.py", line 132, in <module>
    precisions2 = plot_pr_curve(config_file='/home/music/Downloads/mmdetection/work_dirs/non_dino/non.py', result_file='/home/music/Downloads/mmdetection/work_dirs/non_dino/result.pkl', metric=cfg.eval)
  File "/home/music/Downloads/mmdetection/pr_curve.py", line 103, in plot_pr_curve
    coco_dt = coco_gt.loadRes(json_results)
  File "/home/music/miniconda3/envs/bird/lib/python3.9/site-packages/pycocotools/coco.py", line 327, in loadRes
    assert set(annsImgIds) == (set(annsImgIds) & set(self.getImgIds())), \
AssertionError: Results do not correspond to current coco set

**Comment by lijoe123** [comment]
找到问题了，我的json文件的地址写错了。请问怎么样实现画各个类别的pr曲线？
